# Generated by Django 4.1.7 on 2023-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Cancelled')], null=True),
        ),
    ]
