# Generated by Django 4.1.7 on 2023-05-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
