# Generated by Django 4.1.7 on 2023-05-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_update_at_prescription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
