# Generated by Django 4.1.7 on 2023-05-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hospitalinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicinegroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicineinstock',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=6),
        ),
    ]
