# Generated by Django 4.1.7 on 2023-05-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
    ]
