# Generated by Django 4.1.7 on 2023-05-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalinventory',
            options={'managed': True},
        ),
    ]
