# Generated by Django 4.1.7 on 2023-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospitalinventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalinventory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Good'), (0, 'Needs to be refilled')], default=1),
        ),
    ]
