# Generated by Django 4.1.7 on 2023-05-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hospitalinventory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'managed': True},
        ),
    ]
