# Generated by Django 4.1.7 on 2023-05-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_medicine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
