# Generated by Django 4.1.7 on 2023-05-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medicine_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True},
        ),
    ]
