# Generated by Django 4.1.7 on 2023-05-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nurse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
