# Generated by Django 4.1.7 on 2023-05-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
    ]
