# Generated by Django 4.1.7 on 2023-05-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_patient_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
